// get profiles
export const LOAD_PROFILES = "LOAD_PROFILES";
export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS";
export const GET_PROFILES_FAIL = "GET_PROFILES_FAIL";
export const REGISTER_PROFILE = "REGISTER_PROFILE";
export const ADD_PROFILE_FAIL = "ADD_PROFILE_FAIL";
